import { Category, CATEGORIES } from './categories';

export type Gender = 'Women' | 'Men' | 'Unisex';

export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  compareAt?: number;
  description: string;
  image: string;
  colors: string[];
  gender: Gender;
  tags: string[];
  rating: number;
}

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const PRODUCTS: Product[] = [
  {
    id: 'c1',
    name: 'Organic Cotton Everyday Tee',
    category: 'clothing',
    price: 32,
    compareAt: 42,
    description: 'Soft GOTS organic cotton tee made for daily wear. Low-impact dyes and a relaxed fit.',
    image: photo('photo-1521572163474-6864f9cf17ab'),
    colors: ['White', 'Green', 'Black'],
    gender: 'Unisex',
    tags: ['organic', 'bestseller'],
    rating: 4.8,
  },
  {
    id: 'c2',
    name: 'Linen Weekend Shirt',
    category: 'clothing',
    price: 68,
    description: 'Breathable European linen shirt that only gets better with every wash.',
    image: photo('photo-1596755094514-f87e34085b2c'),
    colors: ['Beige', 'White', 'Blue'],
    gender: 'Men',
    tags: ['linen'],
    rating: 4.6,
  },
  {
    id: 'c3',
    name: 'Recycled Fleece Hoodie',
    category: 'clothing',
    price: 74,
    description: 'Cozy hoodie knit from recycled bottles. Fair-trade sewn and built to last.',
    image: photo('photo-1556821840-3a63f95609a7'),
    colors: ['Green', 'Black', 'Brown'],
    gender: 'Unisex',
    tags: ['recycled'],
    rating: 4.7,
  },
  {
    id: 'c4',
    name: 'Vintage-Wash Hemp Jeans',
    category: 'clothing',
    price: 96,
    compareAt: 120,
    description: 'Durable hemp-cotton denim with a vintage wash. No distress chemicals.',
    image: photo('photo-1542272604-787c3835535d'),
    colors: ['Blue', 'Black'],
    gender: 'Women',
    tags: ['hemp'],
    rating: 4.5,
  },
  {
    id: 'c5',
    name: 'Tencel Wrap Dress',
    category: 'clothing',
    price: 88,
    description: 'Fluid Tencel wrap dress that drapes softly and uses closed-loop fibers.',
    image: photo('photo-1515886657613-9f3515e0c79f'),
    colors: ['Green', 'Beige', 'Black'],
    gender: 'Women',
    tags: ['tencel'],
    rating: 4.9,
  },
  {
    id: 'c6',
    name: 'Merino Layering Cardigan',
    category: 'clothing',
    price: 110,
    description: 'Traceable merino cardigan for cool mornings. Naturally odor-resistant.',
    image: photo('photo-1434389677669-e08b4cac3105'),
    colors: ['Brown', 'Beige', 'Green'],
    gender: 'Men',
    tags: ['wool'],
    rating: 4.4,
  },
  {
    id: 'f1',
    name: 'Fair Trade Forest Coffee',
    category: 'food',
    price: 18,
    description: 'Shade-grown beans from small farms. Compostable bag, bright chocolate notes.',
    image: photo('photo-1447933601403-0c6688de566e'),
    colors: ['Brown', 'Black'],
    gender: 'Unisex',
    tags: ['organic', 'fair-trade'],
    rating: 4.8,
  },
  {
    id: 'f2',
    name: 'Organic Pantry Oats',
    category: 'food',
    price: 12,
    description: 'Rolled oats in a refill-friendly kraft pouch. Grown without synthetic pesticides.',
    image: photo('photo-1517686469429-8bdb88b9f907'),
    colors: ['Beige'],
    gender: 'Unisex',
    tags: ['organic', 'vegan'],
    rating: 4.6,
  },
  {
    id: 'f3',
    name: 'Refill Glass Pantry Jars',
    category: 'food',
    price: 36,
    description: 'Set of four airtight jars for bulk shopping. Skip the single-use plastic.',
    image: photo('photo-1584473457406-6240486418e9'),
    colors: ['Clear', 'Green'],
    gender: 'Unisex',
    tags: ['zero-waste'],
    rating: 4.7,
  },
  {
    id: 'f4',
    name: 'Weekly Organic Produce Box',
    category: 'food',
    price: 42,
    description: 'Seasonal fruits and vegetables from local growers. Packed in reusable crates.',
    image: photo('photo-1542838132-92c53300491e'),
    colors: ['Green', 'Red'],
    gender: 'Unisex',
    tags: ['organic', 'local'],
    rating: 4.9,
  },
  {
    id: 'f5',
    name: 'Wildflower Honey',
    category: 'food',
    price: 16,
    description: 'Raw honey from small apiaries. Glass jar, no plastic squeeze bottles.',
    image: photo('photo-1558642452-9d2a7deb7f62'),
    colors: ['Gold', 'Clear'],
    gender: 'Unisex',
    tags: ['local'],
    rating: 4.5,
  },
  {
    id: 's1',
    name: 'Refillable Botanic Serum',
    category: 'skincare',
    price: 38,
    description: 'Vitamin-rich facial serum in a refillable glass dropper bottle.',
    image: photo('photo-1556228720-195a672e8a03'),
    colors: ['Clear', 'Green'],
    gender: 'Unisex',
    tags: ['refillable', 'vegan'],
    rating: 4.8,
  },
  {
    id: 's2',
    name: 'Bamboo Toothbrush Set',
    category: 'skincare',
    price: 14,
    description: 'Four compostable bamboo brushes with plant-based bristles.',
    image: photo('photo-1607613009820-a29f7bb81c04'),
    colors: ['Beige', 'Green'],
    gender: 'Unisex',
    tags: ['zero-waste'],
    rating: 4.6,
  },
  {
    id: 's3',
    name: 'Cedarwood Shampoo Bar',
    category: 'skincare',
    price: 16,
    description: 'Plastic-free shampoo bar that lasts as long as two bottles.',
    image: photo('photo-1608571423902-eed4a9ab2063'),
    colors: ['Brown', 'Beige'],
    gender: 'Men',
    tags: ['plastic-free'],
    rating: 4.4,
  },
  {
    id: 's4',
    name: 'Rose Clay Face Mask',
    category: 'skincare',
    price: 24,
    description: 'Mineral clay mask in a recyclable tin. Calms and gently brightens.',
    image: photo('photo-1598440947619-2c35fc9aa908'),
    colors: ['Pink', 'Beige'],
    gender: 'Women',
    tags: ['vegan'],
    rating: 4.7,
  },
  {
    id: 's5',
    name: 'Daily Glow Moisturizer',
    category: 'skincare',
    price: 29,
    description: 'Lightweight cream with jojoba and aloe. Jar is made from recycled glass.',
    image: photo('photo-1571875257727-256c39da42af'),
    colors: ['White', 'Green'],
    gender: 'Women',
    tags: ['organic'],
    rating: 4.5,
  },
  {
    id: 'k1',
    name: 'Olive Wood Utensil Set',
    category: 'kitchen',
    price: 34,
    description: 'Hand-carved serving utensils that replace disposable kitchen tools.',
    image: photo('photo-1556909114-f6e7ad7d3136'),
    colors: ['Brown'],
    gender: 'Unisex',
    tags: ['handmade'],
    rating: 4.8,
  },
  {
    id: 'k2',
    name: 'Beeswax Table Candles',
    category: 'kitchen',
    price: 22,
    description: 'Clean-burning beeswax tapers. No paraffin, no synthetic fragrance.',
    image: photo('photo-1603006905003-be4810980177'),
    colors: ['Gold', 'Beige'],
    gender: 'Unisex',
    tags: ['natural'],
    rating: 4.6,
  },
  {
    id: 'k3',
    name: 'Recycled Glass Tumblers',
    category: 'kitchen',
    price: 40,
    description: 'Set of four tumblers blown from recycled glass. Dishwasher safe.',
    image: photo('photo-1513558161293-cdaf765ed2fd'),
    colors: ['Clear', 'Green'],
    gender: 'Unisex',
    tags: ['recycled'],
    rating: 4.7,
  },
  {
    id: 'k4',
    name: 'Organic Cotton Kitchen Towels',
    category: 'kitchen',
    price: 28,
    description: 'Absorbent towels that replace paper rolls. Soften with every wash.',
    image: photo('photo-1583845112203-29329902332e'),
    colors: ['White', 'Beige', 'Green'],
    gender: 'Unisex',
    tags: ['organic'],
    rating: 4.5,
  },
  {
    id: 'k5',
    name: 'Cast Iron Everyday Skillet',
    category: 'kitchen',
    price: 64,
    description: 'One pan for a lifetime. Naturally non-stick once seasoned.',
    image: photo('photo-1556910103-1c02745aae4d'),
    colors: ['Black'],
    gender: 'Unisex',
    tags: ['durable'],
    rating: 4.9,
  },
  {
    id: 'e1',
    name: 'Refurbished Wireless Headphones',
    category: 'electronics',
    price: 89,
    compareAt: 179,
    description: 'Certified refurbished over-ears. Tested, cleaned, and warrantied for a year.',
    image: photo('photo-1505740420928-5e560c06d30e'),
    colors: ['Black', 'White'],
    gender: 'Unisex',
    tags: ['refurbished'],
    rating: 4.6,
  },
  {
    id: 'e2',
    name: 'Refurbished 13" Laptop',
    category: 'electronics',
    price: 420,
    compareAt: 899,
    description: 'Fully tested laptop with a new battery. Keeps e-waste out of landfill.',
    image: photo('photo-1496181133206-80ce9b88a853'),
    colors: ['Silver', 'Black'],
    gender: 'Unisex',
    tags: ['refurbished'],
    rating: 4.5,
  },
  {
    id: 'e3',
    name: 'Renewed Smartphone',
    category: 'electronics',
    price: 249,
    compareAt: 699,
    description: 'Grade-A renewed phone with a fair-trade repair history.',
    image: photo('photo-1511707171634-5f897ff02aa9'),
    colors: ['Black', 'Blue', 'White'],
    gender: 'Unisex',
    tags: ['refurbished'],
    rating: 4.4,
  },
  {
    id: 'e4',
    name: 'Portable Solar Charger',
    category: 'electronics',
    price: 58,
    description: 'Fold-out solar panel for weekend trips. Charge phones without the grid.',
    image: photo('photo-1509391366360-2e959784a276'),
    colors: ['Black', 'Green'],
    gender: 'Unisex',
    tags: ['solar'],
    rating: 4.3,
  },
  {
    id: 'e5',
    name: 'Refurbished Bluetooth Speaker',
    category: 'electronics',
    price: 45,
    compareAt: 99,
    description: 'Rich sound, restored housing, and a six-month warranty.',
    image: photo('photo-1608043152269-423dbba4e7e1'),
    colors: ['Black', 'Brown'],
    gender: 'Unisex',
    tags: ['refurbished'],
    rating: 4.5,
  },
  {
    id: 'g1',
    name: 'Terracotta Herb Pots',
    category: 'garden',
    price: 26,
    description: 'Breathable clay pots for kitchen herbs. Includes drainage saucers.',
    image: photo('photo-1485955900006-10f4d324d411'),
    colors: ['Terracotta', 'Beige'],
    gender: 'Unisex',
    tags: ['indoor'],
    rating: 4.7,
  },
  {
    id: 'g2',
    name: 'Hand Garden Tool Set',
    category: 'garden',
    price: 32,
    description: 'FSC wood handles and recycled steel. Built for years of planting.',
    image: photo('photo-1416879595882-3373a0480b5b'),
    colors: ['Brown', 'Green'],
    gender: 'Unisex',
    tags: ['outdoor'],
    rating: 4.6,
  },
  {
    id: 'g3',
    name: 'Pollinator Seed Kit',
    category: 'garden',
    price: 15,
    description: 'Native wildflower mix that feeds bees and butterflies.',
    image: photo('photo-1466692476866-aef36ba3040d'),
    colors: ['Green', 'Gold'],
    gender: 'Unisex',
    tags: ['outdoor'],
    rating: 4.8,
  },
  {
    id: 'g4',
    name: 'Countertop Compost Caddy',
    category: 'garden',
    price: 28,
    description: 'Charcoal-filter caddy for scraps. Turn leftovers into soil.',
    image: photo('photo-1542601906990-b4d3fb778b09'),
    colors: ['Green', 'White'],
    gender: 'Unisex',
    tags: ['indoor', 'zero-waste'],
    rating: 4.5,
  },
  {
    id: 'g5',
    name: 'Succulent Starter Trio',
    category: 'garden',
    price: 24,
    description: 'Three easy-care succulents in recycled-paper pots.',
    image: photo('photo-1459411552884-841db9b3cc2a'),
    colors: ['Green', 'Terracotta'],
    gender: 'Unisex',
    tags: ['indoor'],
    rating: 4.9,
  },
];

export function productsByCategory(slug: string | null | undefined): Product[] {
  if (!slug) {
    return PRODUCTS;
  }
  return PRODUCTS.filter((product) => product.category === slug);
}

export function productById(id: string): Product | undefined {
  return PRODUCTS.find((product) => product.id === id);
}

export function popularProducts(): Product[] {
  return PRODUCTS.filter((product) => product.rating >= 4.7).slice(0, 8);
}

export function categoryOf(slug: string | null | undefined): Category | undefined {
  return CATEGORIES.find((category) => category.slug === slug);
}
